version: '3.8'

services:
  nginx:
    build: ./nginx/
    container_name: sb-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - web_data:/var/www
      - nginx:/etc/nginx
  php:
    image: php:7.0-fpm
    build: ./php/
    container_name: sb-php
    restart: always
    volumes:
      - web_data:/var/www

volumes:
  web_data:
  nginx: