version: '3.8'

services:
  sb:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: sb-php
    restart: always
    working_dir: /var/www
    volumes:
      - web_data:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: sb-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - web_data:/var/www
      - nginx:/etc/nginx

volumes:
  web_data:
  nginx: